### ISSUE TITLE
Forces, and how to implement them

### ISSUE THREAD

**Issue by M-Blomqvist** [INDAPlus20/isaklar-ahanifi-maltebl-lervik-project#7]

**Comment by axellervik** [comment]
# Notes 
aka important things to keep in mind or something
## Generic force vector stuff
- The position of a particle never changes if there is no velocity, and there is no change in velocity unless a force causes it to accelerate (assuming particles can't change mass). Thus the motion of a body is entirely dependent on whatever force-vector acts on it. 
- Fun fact: contrary to velocity and position, a force can be changed however one likes from one moment to the next (with exception to constant ones such as gravity).
- The acceleration of a particle is calculated by dividing the force by mass, which means no particle can have zero mass. However, this means that to make an object immovable we simply set its mass to be infinite. Very useful!!
- With regards to previous point it's more practical to store the inverted mass in an object, which means that to make a body immovable we simply set its inverse_mass to 0. 
- To avoid confusion it could be smart to use functions like set_mass and set_inverse_mass instead of changing it directly. Thus we'd only have to use set_inverse_mass for immovable objects. 

## More specific gravity stuff
- The law of universal gravitation (f = G\*m1\*m2/r^2) can be simplified to f = mg if we assume the physics engine is meant to simulate stuff happening on a planet. In this equation, small g is a super cool constant that includes big G and the size+mass of the planet. 
- Using f = m \* g with a = 1/m \* f gives us a = g. Thus gravity can be directly applied as acceleration to skip some calculations. 
- If we have the y-direction as positive upwards then the gravity acceleration vector will apply a constant [0 -g 0] to all objects that aren't immovable. That last part is important, as skipping the force-divided-by-mass calculation means we must avoid applying it to all objects with an inverse_mass of 0. Or we can simply skip the shortcut of course.

*to be continued*

**Comment by isakvlarsson** [comment]
Isn't this closeable?

**Comment by axellervik** [comment]
I guess it is. Affiliated branch is mostly useless atm and a the useful parts of the code got put elsewhere so never got around to closing it. Will do so now.
